# Generated by Django 4.0.4 on 2022-05-16 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='nominee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('nominee_name', models.CharField(max_length=20)),
                ('nominee_mobile', models.CharField(max_length=10, null=True)),
                ('nominee_email', models.EmailField(max_length=254)),
                ('relation', models.CharField(choices=[('father', 'Father'), ('mother', 'Mother'), ('spouse', 'Spouse'), ('brother', 'Brother'), ('sister', 'Sister'), ('friend', 'Friend')], default='spouse', max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Organ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('blood_group', models.CharField(choices=[('A+', 'A Positive'), ('A-', 'A Negative'), ('B+', 'B Positive'), ('B-', 'B Negative'), ('AB+', 'Ab Positive'), ('AB-', 'Ab Negative'), ('O+', 'O Positive'), ('O-', 'O Negative')], default='A+', max_length=100)),
                ('organ_age', models.IntegerField(null=True)),
                ('organ_type', models.CharField(choices=[('eye', 'Eye'), ('kidney', 'Kidney'), ('heart', 'Heart'), ('liver', 'Liver'), ('pancreas', 'Pancreas'), ('lungus', 'Lungus')], default='eye', max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('location', models.CharField(default=' ', max_length=100)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='post_like_count',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_like', models.IntegerField(default=0, editable=False)),
                ('count_dislike', models.IntegerField(default=0, editable=False)),
                ('post_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_like_count', to='MediDonor.post')),
            ],
        ),
    ]
