# Generated by Django 4.0.4 on 2022-05-16 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MediDonor', '0001_initial'),
        ('MediUser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_like_count',
            name='user_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_like_count', to='MediUser.mediuser'),
        ),
        migrations.AddField(
            model_name='post',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post', to='MediUser.mediuser'),
        ),
        migrations.AddField(
            model_name='organ',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organ', to='MediUser.mediuser'),
        ),
        migrations.AddField(
            model_name='nominee',
            name='donor_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Nominee', to='MediUser.mediuser'),
        ),
    ]
