# Generated by Django 4.0.4 on 2022-05-16 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.FloatField()),
                ('payment_id', models.CharField(max_length=100)),
                ('email', models.EmailField(default='', max_length=254)),
                ('status', models.CharField(choices=[('process', 'Process'), ('success', 'Success'), ('fail', 'Fail')], default='process', max_length=200)),
            ],
        ),
    ]
